from enum import Enum


class LogCategories(Enum):
    GLOBAL = "ALL-CATEGORIES"
    CREATEDCHANNELS = "CREATEDCHANNELS"
    UPDATEDCHANNELS = "UPDATEDCHANNELS"
    DELETEDCHANNELS = "DELETEDCHANNELS"
    CREATEDINVITES = "CREATEDINVITES"
    MEMBERUPDATES = "MEMBERUPDATES"
    MEMBERMOVED = "MEMBERMOVED"
    MEMBERJOINED = "MEMBERJOINED"
    MEMBERLEFT = "MEMBERLEFT"
    EDITEDMESSAGES = "EDITEDMESSAGES"
    DELETEDMESSAGES = "DELETEDMESSAGES"
    CREATEDROLES = "CREATEDROLES"
    UPDATEDROLES = "UPDATEDROLES"
    DELETEDROLES = "DELETEDROLES"
