[project]
name = "winter-dragon"
version = "0.3.0"
description = "A versatile Discord bot with moderation, utility, and entertainment features"
readme = "README.md"
requires-python = ">=3.15"
license = "MIT"
license-files = ["LICENSE.md"]
authors = [
  {name = "HEROgold"}
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.15",
  "Operating System :: OS Independent",
  "Topic :: Communications :: Chat",
  "Topic :: Internet",
  "Framework :: AsyncIO"
]
dependencies = [
  "wd-bot",
  "wd-config",
  "wd-core",
  "wd-db",
  "wd-discord",
  "wd-errors",
  "wd-types",
]

[project.optional-dependencies]
docs = [
  "mkdocs>=1.5.0",
  "mkdocs-material>=9.4.0",
  "mkdocs-include-markdown-plugin>=6.0.0",
]

[tool.uv]
package = true

[tool.ty.environment]
root = ["./src"]

[build-system]
requires = ["uv_build>=0.11.7,<0.12.0"]
build-backend = "uv_build"

[tool.uv.workspace]
members = [
    "wd-core",
    "wd-discord",
    "wd-bot",
    "wd-db",
    "wd-errors",
    "wd-types",
    "wd-config",
]

[tool.uv.sources]
wd-types = { workspace = true }
wd-bot = { workspace = true }
wd-core = { workspace = true }
wd-db = { workspace = true }
wd-discord = { workspace = true }
wd-errors = { workspace = true }
wd-config = { workspace = true }
