indent-width = 4
line-length = 128
target-version = "py315"
unsafe-fixes = true

[format]
indent-style = "space"
line-ending = "auto"
quote-style = "double"
skip-magic-trailing-comma = false

[lint]
exclude = ["build", "dist", "venv"]
select = ["ALL"]
ignore = ["D105"]

[lint.isort]
required-imports = [
  "from __future__ import annotations",
]
lines-after-imports = 2
