[project]
dependencies = [
    "fastapi[standard]>=0.1.0",
    "uvicorn>=0.34.0",
]
description = "Add your description here"
name = "backend"
readme = "README.md"
requires-python = ">=3.12"
version = "0.1.0"
