from fastapi import FastAPI

from winter_dragon.config import Environments, GlobalSettings

from .v1 import router as v1_router


def create_app() -> FastAPI:
    """Create and configure the FastAPI application."""
    app = FastAPI(
        title="Winter Dragon Bot API", version="1.0.0", description="API for Winter Dragon Bot, autogenerated from models."
    )
    app.include_router(v1_router)
    return app


# For ASGI servers (e.g. uvicorn)
app = create_app()

# Enable debugpy for remote debugging in development
if GlobalSettings.environment == Environments.development:
    try:
        import debugpy  # pyright: ignore[reportMissingImports] # noqa: T100  # ty:ignore[unresolved-import]

        debugpy.listen(("0.0.0.0", 5678))  # noqa: S104, T100
        print("debugpy listening on 0.0.0.0:5678")  # noqa: T201
    except ImportError:
        print("debugpy not installed; skipping remote debug setup.")  # noqa: T201
