apiVersion: 1

datasources:
  - name: Winter Dragon Postgres
    type: postgres
    uid: winter-dragon-postgres
    access: proxy
    url: postgres:5432
    database: winter_dragon
    user: postgres
    isDefault: true
    editable: true
    jsonData:
      sslmode: disable
      postgresVersion: 1400
      timescaledb: false
    secureJsonData:
      password: ${DB_PASSWORD:-postgres}
