"""The database package for the Winter Dragon project."""

from sqlmodel import SQLModel

from .constants import SessionMixin, session
from .tables import (
    AssociationUserCommand,
    AssociationUserHangman,
    AssociationUserLobby,
    AuditLog,
    AutoAssignRole,
    AutoChannels,
    AutoChannelSettings,
    AutoReAssign,
    CarFuels,
    Channels,
    CommandGroups,
    Commands,
    DisabledCommands,
    Games,
    GuildCommands,
    GuildRoles,
    Guilds,
    Hangmen,
    Infractions,
    Lobbies,
    LobbyStatus,
    LookingForGroup,
    Messages,
    NhieQuestion,
    Presence,
    Reminder,
    ResultMassiveMultiplayer,
    Roles,
    SteamSale,
    SteamUsers,
    Suggestions,
    SyncBanGuild,
    SyncBanUser,
    UserRoles,
    Users,
    Welcome,
    WyrQuestion,
)


__all__ = [
    "AssociationUserCommand",
    "AssociationUserHangman",
    "AssociationUserLobby",
    "AuditLog",
    "AutoAssignRole",
    "AutoChannelSettings",
    "AutoChannels",
    "AutoReAssign",
    "CarFuels",
    "Channels",
    "CommandGroups",
    "Commands",
    "DisabledCommands",
    "Games",
    "GuildCommands",
    "GuildRoles",
    "Guilds",
    "Hangmen",
    "Infractions",
    "Lobbies",
    "LobbyStatus",
    "LookingForGroup",
    "Messages",
    "NhieQuestion",
    "Presence",
    "Reminder",
    "ResultMassiveMultiplayer",
    "Roles",
    "SQLModel",
    "SessionMixin",
    "SteamSale",
    "SteamUsers",
    "Suggestions",
    "SyncBanGuild",
    "SyncBanUser",
    "UserRoles",
    "Users",
    "Welcome",
    "WyrQuestion",
    "session",
]
