FROM python:3.13-slim

COPY config.ini config.ini
ADD database/ database/
ADD bot/ bot/

# Ensure that we install db first, as its a dependency of the bot
RUN pip3.13 install database/
RUN pip3.13 install bot/

CMD ["python3", "-m", "wd_bot"]
