FROM python:3.13-slim

ADD config.ini config.ini
ADD database/ database/
ADD bot/ bot/

# Ensure that we install db first, as its a dependency of the bot
RUN pip install -e database/
RUN pip install -e bot/

CMD ["python3", "-m", "winter_dragon.bot"]
