FROM python:3.12-slim

WORKDIR /app

COPY /website /app
COPY /database /database
COPY /tools /tools
COPY /website/main.py main.py

RUN pip3.12 install -r website/requirements.txt

CMD ["python3", "main.py"]
