FROM python:3.12-slim

WORKDIR /app

COPY website/requirements.txt requirements.txt
RUN pip3.12 install -r requirements.txt

COPY /database /database
COPY /tools /tools
COPY /website /app
COPY /website/main.py main.py

CMD ["python3", "main.py"]
