"""Typed @overload signatures for wd_discord.gateway.dispatch.parse_dispatch.

GENERATED FILE - do not hand-edit. Regenerate with:

    uv run wd-discord/scripts/generate_dispatch_overloads.py

One overload per wd_discord.gateway.events.EventName member, mapping its literal name to
its payload TypedDict and model DiscordModel type by the PascalCase(event name) convention
(see generate_dispatch_overloads.py's _MODEL_NAME_OVERRIDES for the one exception). Most of the referenced
Payload/Model names below don't exist yet as real classes in events.py - that's a visible
TODO (an unresolved-name error from the type checker), not a bug in this file: build the
pair in events.py, then regenerate to pick it up.
"""

from collections.abc import Mapping
from typing import Literal, overload

from wd_discord.models import DiscordModel

from .events import EventName, GuildCreate, GuildCreatePayload, Message, MessageCreatePayload, RawEvent

@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_CREATE], data: MessageCreatePayload) -> Message: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_CREATE], data: GuildCreatePayload) -> GuildCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.RESUMED], data: ResumedPayload) -> Resumed: ...
@overload
def parse_dispatch(
    name: Literal[EventName.APPLICATION_COMMAND_PERMISSIONS_UPDATE], data: ApplicationCommandPermissionsUpdatePayload
) -> ApplicationCommandPermissionsUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.AUTO_MODERATION_RULE_CREATE], data: AutoModerationRuleCreatePayload
) -> AutoModerationRuleCreate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.AUTO_MODERATION_RULE_UPDATE], data: AutoModerationRuleUpdatePayload
) -> AutoModerationRuleUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.AUTO_MODERATION_RULE_DELETE], data: AutoModerationRuleDeletePayload
) -> AutoModerationRuleDelete: ...
@overload
def parse_dispatch(
    name: Literal[EventName.AUTO_MODERATION_ACTION_EXECUTION], data: AutoModerationActionExecutionPayload
) -> AutoModerationActionExecution: ...
@overload
def parse_dispatch(name: Literal[EventName.CHANNEL_CREATE], data: ChannelCreatePayload) -> ChannelCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.CHANNEL_UPDATE], data: ChannelUpdatePayload) -> ChannelUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.CHANNEL_DELETE], data: ChannelDeletePayload) -> ChannelDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.CHANNEL_PINS_UPDATE], data: ChannelPinsUpdatePayload) -> ChannelPinsUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_CREATE], data: ThreadCreatePayload) -> ThreadCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_UPDATE], data: ThreadUpdatePayload) -> ThreadUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_DELETE], data: ThreadDeletePayload) -> ThreadDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_LIST_SYNC], data: ThreadListSyncPayload) -> ThreadListSync: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_MEMBER_UPDATE], data: ThreadMemberUpdatePayload) -> ThreadMemberUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.THREAD_MEMBERS_UPDATE], data: ThreadMembersUpdatePayload) -> ThreadMembersUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.ENTITLEMENT_CREATE], data: EntitlementCreatePayload) -> EntitlementCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.ENTITLEMENT_UPDATE], data: EntitlementUpdatePayload) -> EntitlementUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.ENTITLEMENT_DELETE], data: EntitlementDeletePayload) -> EntitlementDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_UPDATE], data: GuildUpdatePayload) -> GuildUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_DELETE], data: GuildDeletePayload) -> GuildDelete: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_AUDIT_LOG_ENTRY_CREATE], data: GuildAuditLogEntryCreatePayload
) -> GuildAuditLogEntryCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_BAN_ADD], data: GuildBanAddPayload) -> GuildBanAdd: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_BAN_REMOVE], data: GuildBanRemovePayload) -> GuildBanRemove: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_EMOJIS_UPDATE], data: GuildEmojisUpdatePayload) -> GuildEmojisUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_STICKERS_UPDATE], data: GuildStickersUpdatePayload) -> GuildStickersUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_INTEGRATIONS_UPDATE], data: GuildIntegrationsUpdatePayload
) -> GuildIntegrationsUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_MEMBER_ADD], data: GuildMemberAddPayload) -> GuildMemberAdd: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_MEMBER_REMOVE], data: GuildMemberRemovePayload) -> GuildMemberRemove: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_MEMBER_UPDATE], data: GuildMemberUpdatePayload) -> GuildMemberUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_MEMBERS_CHUNK], data: GuildMembersChunkPayload) -> GuildMembersChunk: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_ROLE_CREATE], data: GuildRoleCreatePayload) -> GuildRoleCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_ROLE_UPDATE], data: GuildRoleUpdatePayload) -> GuildRoleUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.GUILD_ROLE_DELETE], data: GuildRoleDeletePayload) -> GuildRoleDelete: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SCHEDULED_EVENT_CREATE], data: GuildScheduledEventCreatePayload
) -> GuildScheduledEventCreate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SCHEDULED_EVENT_UPDATE], data: GuildScheduledEventUpdatePayload
) -> GuildScheduledEventUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SCHEDULED_EVENT_DELETE], data: GuildScheduledEventDeletePayload
) -> GuildScheduledEventDelete: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SCHEDULED_EVENT_USER_ADD], data: GuildScheduledEventUserAddPayload
) -> GuildScheduledEventUserAdd: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SCHEDULED_EVENT_USER_REMOVE], data: GuildScheduledEventUserRemovePayload
) -> GuildScheduledEventUserRemove: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SOUNDBOARD_SOUND_CREATE], data: GuildSoundboardSoundCreatePayload
) -> GuildSoundboardSoundCreate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SOUNDBOARD_SOUND_UPDATE], data: GuildSoundboardSoundUpdatePayload
) -> GuildSoundboardSoundUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SOUNDBOARD_SOUND_DELETE], data: GuildSoundboardSoundDeletePayload
) -> GuildSoundboardSoundDelete: ...
@overload
def parse_dispatch(
    name: Literal[EventName.GUILD_SOUNDBOARD_SOUNDS_UPDATE], data: GuildSoundboardSoundsUpdatePayload
) -> GuildSoundboardSoundsUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.SOUNDBOARD_SOUNDS], data: SoundboardSoundsPayload) -> SoundboardSounds: ...
@overload
def parse_dispatch(name: Literal[EventName.INTEGRATION_CREATE], data: IntegrationCreatePayload) -> IntegrationCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.INTEGRATION_UPDATE], data: IntegrationUpdatePayload) -> IntegrationUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.INTEGRATION_DELETE], data: IntegrationDeletePayload) -> IntegrationDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.INTERACTION_CREATE], data: InteractionCreatePayload) -> InteractionCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.INVITE_CREATE], data: InviteCreatePayload) -> InviteCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.INVITE_DELETE], data: InviteDeletePayload) -> InviteDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_UPDATE], data: MessageUpdatePayload) -> MessageUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_DELETE], data: MessageDeletePayload) -> MessageDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_DELETE_BULK], data: MessageDeleteBulkPayload) -> MessageDeleteBulk: ...
@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_REACTION_ADD], data: MessageReactionAddPayload) -> MessageReactionAdd: ...
@overload
def parse_dispatch(
    name: Literal[EventName.MESSAGE_REACTION_REMOVE], data: MessageReactionRemovePayload
) -> MessageReactionRemove: ...
@overload
def parse_dispatch(
    name: Literal[EventName.MESSAGE_REACTION_REMOVE_ALL], data: MessageReactionRemoveAllPayload
) -> MessageReactionRemoveAll: ...
@overload
def parse_dispatch(
    name: Literal[EventName.MESSAGE_REACTION_REMOVE_EMOJI], data: MessageReactionRemoveEmojiPayload
) -> MessageReactionRemoveEmoji: ...
@overload
def parse_dispatch(name: Literal[EventName.MESSAGE_POLL_VOTE_ADD], data: MessagePollVoteAddPayload) -> MessagePollVoteAdd: ...
@overload
def parse_dispatch(
    name: Literal[EventName.MESSAGE_POLL_VOTE_REMOVE], data: MessagePollVoteRemovePayload
) -> MessagePollVoteRemove: ...
@overload
def parse_dispatch(name: Literal[EventName.PRESENCE_UPDATE], data: PresenceUpdatePayload) -> PresenceUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.STAGE_INSTANCE_CREATE], data: StageInstanceCreatePayload) -> StageInstanceCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.STAGE_INSTANCE_UPDATE], data: StageInstanceUpdatePayload) -> StageInstanceUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.STAGE_INSTANCE_DELETE], data: StageInstanceDeletePayload) -> StageInstanceDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.SUBSCRIPTION_CREATE], data: SubscriptionCreatePayload) -> SubscriptionCreate: ...
@overload
def parse_dispatch(name: Literal[EventName.SUBSCRIPTION_UPDATE], data: SubscriptionUpdatePayload) -> SubscriptionUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.SUBSCRIPTION_DELETE], data: SubscriptionDeletePayload) -> SubscriptionDelete: ...
@overload
def parse_dispatch(name: Literal[EventName.TYPING_START], data: TypingStartPayload) -> TypingStart: ...
@overload
def parse_dispatch(name: Literal[EventName.USER_UPDATE], data: UserUpdatePayload) -> UserUpdate: ...
@overload
def parse_dispatch(
    name: Literal[EventName.VOICE_CHANNEL_EFFECT_SEND], data: VoiceChannelEffectSendPayload
) -> VoiceChannelEffectSend: ...
@overload
def parse_dispatch(name: Literal[EventName.VOICE_STATE_UPDATE], data: VoiceStateUpdatePayload) -> VoiceStateUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.VOICE_SERVER_UPDATE], data: VoiceServerUpdatePayload) -> VoiceServerUpdate: ...
@overload
def parse_dispatch(name: Literal[EventName.WEBHOOKS_UPDATE], data: WebhooksUpdatePayload) -> WebhooksUpdate: ...
@overload
def parse_dispatch(name: str, data: Mapping[str, object]) -> DiscordModel: ...
